/*
====================================================
Ticket 6: Pareto Analysis (80/20 Rule)
====================================================

Business Question:
What percentage of total revenue is generated by the top 20% of customers?

Business Context:
Businesses often observe that a small percentage of customers generate a large share of revenue. This analysis helps identify customer concentration risk and informs retention and loyalty strategies.

KPI:
- Customer Revenue = SUM(order_amount)
- Revenue Contribution % =
  (Customer Revenue / Total Revenue) * 100

Grain:
Intermediate:
One row = One customer

Final:
Contribution of top 20% customers to total revenue 

SQL Concepts Used:
- CTEs
- Window Functions
- ROW_NUMBER()
- Percentage Calculations
====================================================
*/

with customer_revenue_rank as
(select c.customer_id, 
c.customer_name,
sum(o.order_amount) as revenue,
row_number()over(order by sum(o.order_amount) desc) as rank_
from customers c
join orders o
on c.customer_id = o.customer_id
where o.order_status = 'Delivered'
group by c.customer_id, c.customer_name),
top_20_Perc_cust as (
select * from customer_revenue_rank
where rank_ <= (select count(customer_id) * 0.2 from customer_revenue_rank))

select ROUND((SELECT SUM(revenue) FROM top_20_perc_cust) * 100.0 /(SELECT SUM(revenue) FROM customer_revenue_rank),2) AS top_20_perc_revenue;
